updated docker compose and pipeline

diff --git a/.devops/code-review-pipelines.yml b/.devops/code-review-pipelines.yml
--- a/.devops/code-review-pipelines.yml
+++ b/.devops/code-review-pipelines.yml
@@ -60,3 +60,37 @@ stages:
               summaryFileLocation: 'build/reports/jacoco/test/jacocoTestReport.xml'
               reportDirectory: 'build/reports/jacoco/test/html'
             displayName: 'Publish Code Coverage on Azure Devops'
+
+  - stage: IntegrationTest
+    dependsOn: [ ]
+    jobs:
+      - job: Integration_Test
+        steps:
+          - script: docker compose up -d
+            displayName: 'Run app with docker-compose'
+          - script: |
+              timeout 180 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8300/actuator/health/liveness)" != "200" ]]; do sleep 5; done' || exit 1
+            displayName: 'Health check pagopa-payment-wallet-scheduler-service'
+          - script: |
+              eventFromQueue=$(az storage message peek \
+                --connection-string "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://localhost:10001/devstoreaccount1" \
+                --queue-name pagopa-wallet-cdc-queue \
+                --output tsv --query '[0].content')
+              
+              expectedDataEvent=$(cat docker-local/wallet-events-producer-testing/data.json)
+
+              eventDataFromQueue=$(echo $eventFromQueue | jq -r '.data')
+              
+              echo "EventDataFromQueue: $eventDataFromQueue"
+              echo "ExpectedEventData: $expectedDataEvent"
+
+              normalized_event_expected=$(echo "$eventDataFromQueue" | jq -S .)
+              normalized_event_from_queue=$(echo "$expectedDataEvent" | jq -S .[0])
+              
+              if [ "$normalized_event_expected" == "$normalized_event_from_queue" ]; then
+                echo "test passed successfully"
+              else
+                echo "fail! unexpected event"
+                exit 1   
+              fi
+            displayName: 'Get cdc event from Azurite queue and validate'
