Update code-review-pipelines.yml

diff --git a/.devops/code-review-pipelines.yml b/.devops/code-review-pipelines.yml
--- a/.devops/code-review-pipelines.yml
+++ b/.devops/code-review-pipelines.yml
@@ -130,3 +130,84 @@ stages:
                 exit 1
               fi
             displayName: 'Get event from Azurite queue and validate'
+
+  - stage: ValidateCDCFlow
+    displayName: "Validate CDC flow"
+    dependsOn: [ ]
+    jobs:
+      - job: Integration_Test
+        steps:
+          - script: |
+              # Retrieve MongoDB password from Azure Key Vault
+              mongoPassword=$(az keyvault secret show --name YOUR_SECRET_NAME --vault-name YOUR_KEYVAULT_NAME --query value -o tsv)
+              
+              # MongoDB connection details
+              mongoHost="pagopa-u-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com"
+              mongoUsername="pagopa-u-weu-ecommerce-cosmos-account"
+              mongoUri="mongodb://${mongoUsername}:${mongoPassword}@${mongoHost}:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@${mongoUsername}@"
+              
+              # Write documents to the payment-wallets DB in the payment-wallet collection
+              databaseName="payment-wallets"
+              collectionName="payment-wallet"
+              jsonFilePath="/automated-test/mongo-events.json"
+              
+              # Insert documents from the JSON file into the MongoDB collection
+              mongoimport --uri "$mongoUri" --db "$databaseName" --collection "$collectionName" --file "$jsonFilePath" --jsonArray
+
+            displayName: 'Insert documents into MongoDB'
+          - script: |
+              sleep 15
+              
+              # Get the first event from the Azure Storage Queue
+              eventFromQueue_1=$(az storage message get \
+                --connection-string "$AZURE_QUEUE_CONNECTION_STRING" \
+                --queue-name pagopa-u-itn-pay-wallet-cdc-queue \
+                --output tsv --query '[0].content')
+              
+              # Get the second event from the Azure Storage Queue
+              eventFromQueue_2=$(az storage message get \
+                --connection-string "$AZURE_QUEUE_CONNECTION_STRING" \
+                --queue-name pagopa-u-itn-pay-wallet-cdc-queue \
+                --output tsv --query '[0].content')
+              
+              # Extract data from both events
+              eventDataFromQueue_1=$(echo "$eventFromQueue_1" | jq -c '.data')
+              eventDataFromQueue_2=$(echo "$eventFromQueue_2" | jq -c '.data')
+              
+              # Use IDs to determine which event is which
+              if [[ "$eventFromQueue_1" == *"00a06383-1495-4b90-88f6-80c5fecf554a"* ]]; then
+                eventDataFromQueueCards="$eventDataFromQueue_1"
+                eventDataFromQueuePaypal="$eventDataFromQueue_2"
+              elif [[ "$eventFromQueue_1" == *"a0a27446-e6d8-47d2-8786-ca393f19c30b"* ]]; then
+                eventDataFromQueuePaypal="$eventDataFromQueue_1"
+                eventDataFromQueueCards="$eventDataFromQueue_2"
+              else
+                echo "Unexpected event ID in eventFromQueue_1"
+                exit 1
+              fi
+              
+              expectedDataEventCards=$(cat integration-test/onboarding-wallet-card.json | jq -c .)
+              expectedDataEventPaypal=$(cat integration-test/onboarding-wallet-paypal.json | jq -c .)
+              
+              echo "EventDataFromQueueCards: $eventDataFromQueueCards"
+              echo "ExpectedEventDataCards: $expectedDataEventCards"
+              
+              echo "EventDataFromQueuePaypal: $eventDataFromQueuePaypal"
+              echo "ExpectedEventDataPaypal: $expectedDataEventPaypal"
+              
+              # Compare the events Cards
+              if [ "$eventDataFromQueueCards" == "$expectedDataEventCards" ]; then
+                echo "CARDS: test passed successfully"
+              else
+                echo "CARDS: fail! unexpected event"
+                exit 1
+              fi
+              
+              # Compare the events Paypal
+              if [ "$eventDataFromQueuePaypal" == "$expectedDataEventPaypal" ]; then
+                echo "PAYPAL: test passed successfully"
+              else
+                echo "PAYPAL: fail! unexpected event"
+                exit 1
+              fi
+            displayName: 'Get event from Azure Storage Queue and validate'
