Update deploy-pipelines.yml

diff --git a/.devops/deploy-pipelines.yml b/.devops/deploy-pipelines.yml
--- a/.devops/deploy-pipelines.yml
+++ b/.devops/deploy-pipelines.yml
@@ -331,72 +331,59 @@ stages:
   # --- END Deploy UAT --- #
 
 
-  # --- START CDC Test suite in UAT --- #
-  - stage: "GenerateWalletEventsForCDC"
+  # --- START of Validate event in Hub (UAT) --- #
+  - stage: "UAT_Testing_Generate_Wallet_Event"
+    displayName: "UAT Testing Generate Wallet Event"
+    dependsOn: [Deploy_UAT_Green ]
     pool:
       vmImage: 'ubuntu-latest'
-    dependsOn: [ Deploy_UAT_Green ]
-    condition: |
-      in(dependencies.Deploy_UAT_Green.result, 'Succeeded', 'Skipped')
     jobs:
-      - job: api_tests_uat
+      - job: ValidateCDCFlow
         displayName: 'Run API Tests DataLake Flow (UAT)'
         steps:
           - script: |
               yarn global add newman
             displayName: 'newman installation'
-
           - script: |
-              newman run --ignore-redirects api-tests/wallet_payment_api.cards.tests.json --environment=api-tests/uat.cards.envs.json --reporters cli,junit --reporter-junit-export Results/cdc-api-TEST.xml  > newman_output.txt
-            displayName: 'Run API tests (UAT)'
-
+              newman run --ignore-redirects api-tests/wallet_payment_api.cards.tests.json --environment=api-tests/uat.cards.envs.json --env-var WALLET_TOKEN_TEST=$(WALLET_TOKEN_TEST) --reporters cli,junit,json > output.txt
+            displayName: 'Run API tests to generate events on Queue for CDC (UAT)'
           - script: |
-              WALLET_ID=$(grep -oP '(?<=WALLET_ID=)[^ ]+' newman_output.txt)
+              # Extract WALLET_ID from report JSON
+              WALLET_ID=$(grep -oP "WALLET_ID=\K[^\']+" output.txt)
+              
+              if [ -z "$WALLET_ID" ]; then
+                echo "Cannot extract WALLET_ID from report"
+                exit 1
+              fi
+              echo "WALLET_ID=$WALLET_ID"
               echo "##vso[task.setvariable variable=WALLET_ID]$WALLET_ID"
-            displayName: 'Export WALLET_ID to environment variable'
-
-          - task: PublishTestResults@2
-            inputs:
-              testRunTitle: "Run API Tests DataLake Flow (UAT)"
-              testResultsFormat: 'JUnit'
-              testResultsFiles: '**/cdc-api-TEST.xml'
-              searchFolder: '$(System.DefaultWorkingDirectory)'
-            condition: succeededOrFailed()
-
-  # --- END of CDC Test suite in UAT --- #
-
-
-  # --- START Validate event in Hub (UAT) --- #
-  - stage: EventHubValidation
-    dependsOn: [ ]
-    jobs:
-      - job: EventHubValidation
-        steps:
+            displayName: 'Extract and export WALLET_ID from JSON report'
           - script: |
               wget https://archive.apache.org/dist/kafka/2.8.0/kafka_2.13-2.8.0.tgz
               tar -xzf kafka_2.13-2.8.0.tgz
               export PATH=$PATH:$PWD/kafka_2.13-2.8.0/bin
               # Verify Kafka installation
               kafka-topics.sh --version
-
-              # wait for a scheduler cycle
-              sleep 15
-
-              # Create the consumer properties file
-              cat <<EOL > consumer.properties
-              sasl.mechanism=PLAIN
-              security.protocol=SASL_SSL
-              sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="\$ConnectionString" password="AZURE_EVENTHUB_CONNECTION_STRING";
-              EOL
-              
+              sleep 4
               # Run the Kafka consumer command
-              eventFromKafka=$(kafka-console-consumer.sh --bootstrap-server $EVENT_HUB_PATH --topic $EVENT_HUB_TOPIC --from-beginning --timeout-ms 5000 --max-messages 1 --consumer.config consumer.properties)
-              expectedDataEventId=$WALLET_ID
+              eventsFromKafka=$(kafka-console-consumer.sh \
+                --bootstrap-server pagopa-u-itn-observ-evh.servicebus.windows.net:9093 \
+                --topic payment-wallet-ingestion-dl \
+                --from-beginning \
+                --timeout-ms 25000 \
+                --consumer-property sasl.mechanism=PLAIN \
+                --consumer-property security.protocol=SASL_SSL \
+                --consumer-property "sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"\$ConnectionString\" password=\"$(AZURE_EVENTHUB_CONNECTION_STRING)\";")
               
-              echo "event found: $eventFromKafka"
-
+              # Filter events by walletId
+              filteredEvents=$(echo "$eventsFromKafka" | jq -c 'select(.walletId == "'$WALLET_ID'")')
+              
+              # Print the latest event from the filtered events
+              latestEvent=$(echo "$filteredEvents" | tail -n 1)
+   
               # Extract the id from the JSON string
-              eventId=$(echo $eventFromKafka | jq -r '.id')
+              eventId=$(echo $latestEvent | jq -r '.walletId')
+              expectedDataEventId=$WALLET_ID
 
               echo "Extracted event ID: $eventId"
               echo "Expected event ID: $expectedDataEventId"
@@ -406,6 +393,21 @@ stages:
               else
                 echo "fail! unexpected event"
                 exit 1   
+              fi
+
+              # Extract the timestamp from the JSON string
+              timestamp=$(echo $latestEvent | jq -r '.timestamp')
+
+              # Get the current time and calculate the time difference
+              currentTime=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
+              timeDifference=$(($(date -d "$currentTime" +%s) - $(date -d "$timestamp" +%s)))
+
+              # Check if the timestamp is less than 30000  ms ago
+              if [ $timeDifference -lt 30000  ]; then
+                echo "timestamp is less than 30000  ms ago"
+              else
+                echo "timestamp is more than 30000  ms ago"
+                exit 1
               fi
             displayName: 'Validate message in Kafka topic'
   # --- END Validate event in Hub (UAT) --- #
